### ISSUE TITLE
Anatomical Region Superclass? 

### ISSUE THREAD

**Issue by Snowotarski** [srobb1/planarian_obo#2]
In talking with Eric Ross a while back we talked about where/how to classify commonly used terms like "Neck" "Parapharyngeal Region" and "Tail Stripe". All regions that do not correspond to a particular cell type, tissue or even organ. I had suggested that a region would be appropriate. Thus I propose a new Superclass, sibling to anatomical structure, called anatomical region to house these. This may also be a space in which to include common anatomical orientation/domain references such as dorsal, ventral, margin, anterior, posterior. It may also be possible to nest it like this: 
Anatomical Region (dorsal, ventral, descriptive regions)> Anatomical Structures
as structures exist within a broader region...

**Comment by cmungall** [comment]
In CARO and Uberon we use 'organism subdivision'. For major subdivisions like neck (which is obviously not homology, but same classification principles apply)

 * [UBERON:0001062](http://purl.obolibrary.org/obo/UBERON_0001062) ! anatomical entity
    * [UBERON:0000465](http://purl.obolibrary.org/obo/UBERON_0000465) ! material anatomical entity
       * [UBERON:0000061](http://purl.obolibrary.org/obo/UBERON_0000061) ! anatomical structure
          * [UBERON:0010000](http://purl.obolibrary.org/obo/UBERON_0010000) ! multicellular anatomical structure
              * [UBERON:0000475](http://purl.obolibrary.org/obo/UBERON_0000475) ! organism subdivision
                 * [UBERON:0000974](http://purl.obolibrary.org/obo/UBERON_0000974) ! neck

**Comment by srobb1** [comment]
This issue was moved to obophenotype/planaria-ontology#11
