### ISSUE TITLE
New Class : Cellular Component

### ISSUE THREAD

**Issue by Snowotarski** [srobb1/planarian_obo#7]
This can eventually be further resolved or obsoleted, but it would be a good place for organelles to live for now. For example, relocating rhabdite here would be appropriate.

**Comment by cmungall** [comment]
We'd be happy to take any organelles into the Gene Ontology. You can then import the desired subset into PLANA

**Comment by srobb1** [comment]
This issue was moved to obophenotype/planaria-ontology#10
